### ISSUE TITLE
Version of utils-decorators

### ISSUE THREAD

**Issue by vlio20** [jgarciaperez/terra-angular-test#1]
Hi, 
I noticed that you started using the utils-decorators library and specifically the throttleAsync decorator - I found a major bug in it so I encourage you to upgrade to version 2.0.1.

**Comment by jgarciaperez** [comment]
<div><br class="Apple-interchange-newline">Thank you very much for the tip!
I will switch to the version you mentioned and update my code.</div>
Thank you very much for the tip! I will switch to the version you mentioned
and update my code.

**Comment by vlio20** [comment]
I would appreciate if you will ⭐ the library ;)
